/**
 * PM2 ecosystem for Marketplace (production).
 * 4 ta process: marketplace-api (4000), marketplace-webapp (2401),
 * marketplace-admin (2402), marketplace-superadmin (2403).
 * Boshqa loyihalardan ajratish uchun nomlarda `marketplace-` prefiks.
 */
module.exports = {
  apps: [
    {
      name: 'marketplace-api',
      cwd: '/opt/marketplace/backend',
      script: 'dist/src/main.js',
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      max_restarts: 10,
      restart_delay: 4000,
      env: { NODE_ENV: 'production' },
      out_file: '/opt/marketplace/logs/api.out.log',
      error_file: '/opt/marketplace/logs/api.err.log',
      time: true,
    },
    {
      name: 'marketplace-webapp',
      cwd: '/opt/marketplace/webapp',
      script: 'node_modules/next/dist/bin/next',
      args: 'start -p 2401',
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      max_restarts: 10,
      env: { NODE_ENV: 'production', BACKEND_URL: 'http://127.0.0.1:2400' },
      out_file: '/opt/marketplace/logs/webapp.out.log',
      error_file: '/opt/marketplace/logs/webapp.err.log',
      time: true,
    },
    {
      name: 'marketplace-admin',
      cwd: '/opt/marketplace/admin',
      script: 'node_modules/next/dist/bin/next',
      args: 'start -p 2402',
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      max_restarts: 10,
      env: { NODE_ENV: 'production', BACKEND_URL: 'http://127.0.0.1:2400' },
      out_file: '/opt/marketplace/logs/admin.out.log',
      error_file: '/opt/marketplace/logs/admin.err.log',
      time: true,
    },
    {
      name: 'marketplace-superadmin',
      cwd: '/opt/marketplace/superadmin',
      script: 'node_modules/next/dist/bin/next',
      args: 'start -p 2403',
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      max_restarts: 10,
      env: { NODE_ENV: 'production', BACKEND_URL: 'http://127.0.0.1:2400' },
      out_file: '/opt/marketplace/logs/superadmin.out.log',
      error_file: '/opt/marketplace/logs/superadmin.err.log',
      time: true,
    },
  ],
};
